name: motorly
description: A new Flutter project.

publish_to: "none"

version: 1.0.73+97
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  moor_flutter: 
  sqflite: 
  flutter_svg: 
  flushbar: 
  firebase_auth:
  firebase_remote_config:
  firebase_crashlytics: 
  firebase_analytics: 
  firebase_core: 
  dartz: 
  dio: 
  flutter_bloc: 
  equatable: 
  bloc: 
  bloc_test: 
  flutter_modular: 
  in_app_review: 
  font_awesome_flutter: 
  url_launcher: 
  permission_handler: 
  image_picker: 
  lottie: 
  carousel_slider: 
  firebase_dynamic_links: 
  shared_preferences: 
  timeline_tile: 
  google_sign_in: 
  flutter_facebook_auth: 
  cloud_firestore: 
  sign_in_with_apple: 
  uuid: 
  share_plus:
  sigv4:
  flutter:
    sdk: flutter  
  shake:
  shimmer:
  in_app_purchase:
  dropdown_plus:
  camera:
  flutter_custom_tabs: 
  recase:
  smart_select:
  cached_network_image: ^3.1.0+1

dev_dependencies:
  effective_dart: ^1.3.0
  freezed_annotation: ^0.15.0
  freezed: ^0.15.1+1
  build_runner: ^2.1.5
  mockito: ^5.0.3
  flutter_launcher_icons: ^0.9.0
  moor_generator: ^4.6.0+1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/icon-android.png"
  image_path_ios: "assets/icon/icon-ios.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/lemon.png
    - assets/car.png
    - assets/favorites_icon.png
    - assets/favorites_icon.svg
    - assets/splash.gif
    - assets/splash.json
    - assets/button.json
    - assets/car.json
    - assets/car-instructions1.json
    - assets/car-instructions2.json
    - assets/splash-animation.riv
    - assets/logo.png
    - assets/icon/
    - assets/stories/
    - assets/bodytype/
    - assets/lessons/
    - assets/ilustrations/
    - assets/shake-scan.json
    - assets/customCamera/
    - assets/makes.json

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova-Bold.otf

    - family: PaytoneOne
      fonts:
        - asset: fonts/Paytone-One.ttf

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - weight: 600
        - asset: fonts/OpenSans-ExtraBold.ttf
        - weight: 700
        - asset: fonts/OpenSans-Light.ttf
        - weight: 300
        - asset: fonts/OpenSans-Regular.ttf
        - weight: 400
